### ISSUE TITLE
One mockito ServiceTest failure: testUpdateWithNullPerson()

### ISSUE THREAD

**Issue by PedroQueiroz1** [PedroQueiroz1/rest-with-spring-boot-and-java#2]
Error:
java.lang.AssertionError: unexpected exception type thrown; expected:<br.com.project.exceptions.RequiredObjectIsNullException> but was:<java.lang.NullPointerException>
...

**Comment by Flotss** [comment]
https://github.com/PedroQueiroz1/rest-with-spring-boot-and-java/blob/21a47156a8dd56371f4ca84f614c31b20983d24d/05_FirstStepsInJavaWithSpringBoot/rest-with-spring-boot-and-java/src/main/java/br/com/project/services/PersonService.java#L72

You just forgot to put back the verification if the person parameter is null
You have to add this : if (person == null) throw new RequiredObjectIsNullException();

**Comment by Flotss** [comment]
if the personne*

**Comment by PedroQueiroz1** [comment]
Oh! I never expected that someone would help me. TYVM!
